#!/system/bin/sh

alias dirname=/system/bin/dirname
alias realpath=/system/bin/realpath

sd=$(dirname "$(realpath "$0")")

exec /system/bin/linker64 $(realpath "$sd/../../bun-android") --no-orphans "$sd/index.js" "$@"
